#     COURSE: Linear algebra: theory and implementation
##    SECTION: Introduction to matrices

#### Instructor: sincxpress.com
##### Course url: https://www.udemy.com/course/linear-algebra-theory-and-implementation/?couponCode=202110

In [8]:
import numpy as np


---
# VIDEO: A zoo of matrices
---


In [12]:

# square vs. rectangular
S = np.random.randn(5,5)
R = np.random.randn(5,2) # 5 rows, 2 columns
print(S), print(' ')
print(R)

# identity
I = np.eye(3)
print(I), print(' ')

# zeros
Z = np.zeros((4,4))  # input is tuple!
# Z = np.zeros(4, 4)  # error
print(Z), print(' ')

# diagonal
D = np.diag([ 1, 2, 3, 5, 2 ])
print(D)

[[-0.35314565  0.61189495 -1.07281747  0.37702751  0.04125853]
 [ 1.1287465   0.18091986  0.1794864  -0.51947862  1.22750935]
 [-0.2904204   0.1963104  -0.00345993 -1.26902573 -0.40922926]
 [ 0.59513696 -0.96859355  0.37253315 -0.35161141 -1.72833004]
 [-0.76011515  0.16823249 -0.60620105 -0.15251605 -1.46466921]]
 
[[-1.95228939 -1.39441498]
 [ 0.4417219   1.1055026 ]
 [ 0.92677678  0.41096837]
 [ 0.67427973  0.38647345]
 [-0.04356852 -0.81820917]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
 
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 5 0]
 [0 0 0 0 2]]


In [17]:
# create triangular matrix from full matrices
S = np.random.randn(5,5)
U = np.triu(S)
L = np.tril(S)
print(S), print(' ')
print(U), print(' ')
print(L), print(' ')

# concatenate matrices (sizes must match!)
A = np.random.randn(3,2)
B = np.random.randn(3,4)
C = np.concatenate((A,B),axis=1)
print(C)

A = np.random.randn(3,2)
B = np.random.randn(4,4)
C = np.concatenate((A,B),axis=1)  # error
print(C)

[[ 4.89980928e-02 -1.51473615e+00 -1.04664197e+00 -1.42103515e+00
  -1.54089372e+00]
 [-1.36761526e+00 -1.15323508e+00 -1.23803460e-01 -1.59844560e+00
   1.19096374e+00]
 [ 7.30872832e-01 -9.66804224e-04  1.39561353e+00  1.90070060e+00
  -7.39380094e-01]
 [-1.11606603e-01 -6.37069598e-01 -1.95883764e+00  5.44616896e-01
   2.28351805e-01]
 [-1.04225843e+00 -4.79995706e-01  1.11450001e+00 -6.85022908e-01
  -7.88024494e-02]]
 
[[ 0.04899809 -1.51473615 -1.04664197 -1.42103515 -1.54089372]
 [ 0.         -1.15323508 -0.12380346 -1.5984456   1.19096374]
 [ 0.          0.          1.39561353  1.9007006  -0.73938009]
 [ 0.          0.          0.          0.5446169   0.22835181]
 [ 0.          0.          0.          0.         -0.07880245]]
 
[[ 4.89980928e-02  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [-1.36761526e+00 -1.15323508e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 7.30872832e-01 -9.66804224e-04  1.39561353e+00  0.00000000e+00
   0.00000000e+00]

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 4


---
# VIDEO: Matrix addition and subtraction
---


In [21]:
# create random matrices
A = np.random.randn(5,4)
B = np.random.randn(5,3)
C = np.random.randn(5,4)

# try to add them
# A+B  # Error
A+C

# "shifting" a matrix
l = .03 # lambda
N = 5  # size of square matrix
D = np.random.randn(N,N) # can only shift a square matrix

Ds = D + l*np.eye(N)
print(D), print(' '), print(Ds)

[[ 1.07527579 -0.13709746  0.57886179 -0.29964717  0.44980047]
 [-0.44812319  1.57775471 -0.94575461  0.69502771  0.98727799]
 [ 2.51055354 -1.41812108  1.5430232   0.08283622 -0.23681078]
 [ 1.21594865  0.61575404  1.81508353  2.38310786  1.19345432]
 [-0.39796434 -1.09138511  2.60110913 -0.08528062 -0.77262507]]
 
[[ 1.10527579 -0.13709746  0.57886179 -0.29964717  0.44980047]
 [-0.44812319  1.60775471 -0.94575461  0.69502771  0.98727799]
 [ 2.51055354 -1.41812108  1.5730232   0.08283622 -0.23681078]
 [ 1.21594865  0.61575404  1.81508353  2.41310786  1.19345432]
 [-0.39796434 -1.09138511  2.60110913 -0.08528062 -0.74262507]]


(None, None, None)


---
# VIDEO: Matrix-scalar multiplication
---


In [22]:
# define matrix and scalar
M = np.array([ [1, 2], [2, 5] ])
s = 2

# pre- and post-multiplication is the same:
print( M*s )
print( s*M )


[[ 2  4]
 [ 4 10]]
[[ 2  4]
 [ 4 10]]


In [23]:
# Code Challenge: is matrix-scalr multiplication a linear operation?
# s(A+B) = sA + sB
m, n = 7, 5

A = np.random.randn(m, n)
B = np.random.randn(m, n)

s = np.random.randn()

resL = s * (A+B)
resR = s*A + s*B

print(resL), print(' ')
print(resR), print(' ')
print(resL - resR)

[[ 1.40162434 -1.0869481   0.89957858  0.75292076 -0.69496405]
 [ 0.50658147 -0.07697785  0.8350357  -1.4081933   0.79379951]
 [-0.11264065  0.19743146  0.11397288 -0.6143676   0.4242942 ]
 [-0.03038289  1.59618081 -1.6805689  -0.18173045  0.25268349]
 [ 0.237116    1.56903081 -0.44472157  0.46042026  0.29873381]
 [-0.17535949 -0.42905281 -0.79689049 -0.71607562 -0.32496967]
 [-1.1394604   0.66406364  0.01482485  0.00902377  0.63418731]]
 
[[ 1.40162434 -1.0869481   0.89957858  0.75292076 -0.69496405]
 [ 0.50658147 -0.07697785  0.8350357  -1.4081933   0.79379951]
 [-0.11264065  0.19743146  0.11397288 -0.6143676   0.4242942 ]
 [-0.03038289  1.59618081 -1.6805689  -0.18173045  0.25268349]
 [ 0.237116    1.56903081 -0.44472157  0.46042026  0.29873381]
 [-0.17535949 -0.42905281 -0.79689049 -0.71607562 -0.32496967]
 [-1.1394604   0.66406364  0.01482485  0.00902377  0.63418731]]
 
[[ 0.00000000e+00  2.22044605e-16  0.00000000e+00  1.11022302e-16
   0.00000000e+00]
 [-1.11022302e-16  0.000000

# VIDEO: Transpose

In [24]:
M = np.array([ [1,2,3],
               [2,3,4] ])

print(M), print('')
print(M.T), print('') # one transpose
print(M.T.T), print('') # double-transpose returns the original matrix

# can also use the function transpose
print(np.transpose(M))

[[1 2 3]
 [2 3 4]]

[[1 2]
 [2 3]
 [3 4]]

[[1 2 3]
 [2 3 4]]

[[1 2]
 [2 3]
 [3 4]]


In [27]:
# warning! be careful when using complex matrices
C = np.array([ [4+1j , 3 , 2-4j] ])

print(C), print('')
print(C.T), print('')
print(np.transpose(C)), print('')

# Note: In MATLAB, the transpose is the Hermitian transpose; 
#       in Python, you need to call the Hermitian explicitly by first converting from an array into a matrix
print(C.conjugate().T) # note the sign flips!
# Another note: the code I used in the video will soon be depreciated; use the above line instead.
print(np.matrix(C).H)


[[4.+1.j 3.+0.j 2.-4.j]]

[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]

[[4.+1.j]
 [3.+0.j]
 [2.-4.j]]

[[4.-1.j]
 [3.-0.j]
 [2.+4.j]]
[[4.-1.j]
 [3.-0.j]
 [2.+4.j]]



---
# VIDEO: Diagonal and trace
---


In [28]:
M = np.round( 6*np.random.randn(4,4) )
print(M), print(' ')
# extract the diagonals
d = np.diag(M)

# notice the two ways of using the diag function
d = np.diag(M) # input is matrix, output is vector
D = np.diag(d) # input is vector, output is matrix
print(d)
print(D)

# trace as sum of diagonal elements, it must be a squre matrix.
tr = np.trace(M)
tr2 = sum( np.diag(M) )
print(tr,tr2)

[[  4.  -7.  -0.   0.]
 [ -9.   2.   5.   8.]
 [ -4.   6.   5.  -1.]
 [ -2.   4. -11. -11.]]
 
[  4.   2.   5. -11.]
[[  4.   0.   0.   0.]
 [  0.   2.   0.   0.]
 [  0.   0.   5.   0.]
 [  0.   0.   0. -11.]]
0.0 0.0


In [29]:
# Code challenge: linearity of trace
# tr(A) + tr(B) == tr(A+B) ?
# tr(l*A) == l*tr(A) ?

m, n = 4, 4
A = np.random.randn(m, n)
B = np.random.randn(m, n)

l = np.random.rand()

print('tr(A+B) = ' + str(np.trace(A+B)))
print('tr(A) + tr(B) = ' + str(np.trace(A) + np.trace(B)))
print()
print('tr(l*A) = ' + str(np.trace(l*A)))
print('l*tr(A) = ' + str(l * np.trace(A)))



tr(A+B) = -2.2618975646220685
tr(A) + tr(B) = -2.2618975646220685

tr(l*A) = -1.8417819587908808
l*tr(A) = -1.8417819587908808



---
# VIDEO: Broadcasting matrix arithmetic
---


In [30]:
# create a matrix
A = np.reshape(np.arange(1,13),(3,4),'F') # F=column, C=row

# and two vectors
r = [ 10, 20, 30, 40 ]
c = [ 100, 200, 300 ]

print(A), print(' ')
print(r), print(' ')
print(c), print(' ');

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
 
[10, 20, 30, 40]
 
[100, 200, 300]
 


In [36]:
# broadcast on the rows 
print(A+r), print(' ')

# broadcast on the columns
# print(A+c)  # ValueError: operands could not be broadcast together with shape(3, 4) (3,)
c_reshaped = np.reshape(c,(len(c),1))
print(c_reshaped)
print(A+c_reshaped) # only works for explicit column vectors


[[11 24 37 50]
 [12 25 38 51]
 [13 26 39 52]]
 
[[100]
 [200]
 [300]]
[[101 104 107 110]
 [202 205 208 211]
 [303 306 309 312]]
