#     COURSE: Linear algebra: theory and implementation
##    SECTION: Matrix rank

#### Instructor: sincxpress.com
##### Course url: https://www.udemy.com/course/linear-algebra-theory-and-implementation/?couponCode=202110

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math


---
# VIDEO: Computing rank: theory and practice
---


In [5]:
# make a matrix
m = 4
n = 6

# create a random matrix: random matrix generates usually full rank matrices!
A = np.random.randn(m,n)  # High probabilty rank 4 with 4 random rows
print(A)

# what is the largest possible rank?
ra = np.linalg.matrix_rank(A)
print('rank = ' + str(ra), '\n')

# set last column to be repeat of penultimate column
B = A
B[:,-1] = B[:,-2]  # make the last two columns same
print(B)

rb = np.linalg.matrix_rank(B)
print('rank = ' + str(rb), '\n')  # Still, the rank is 4!

C = A
C[-1, :] = C[-2, :]  # make the last two rows same -> Rank 3
print(C)

rb = np.linalg.matrix_rank(C)
print('rank = ' + str(rb))

[[-1.74725858 -2.52083677  1.07458242  1.23982343  0.44724371  0.86996332]
 [-0.04464538  0.76412724 -0.93559785  1.64392921 -0.3096506  -0.57648908]
 [ 0.75478467  0.02678163 -0.23610617  1.00405024 -0.65837617  1.11444385]
 [-0.37989363  0.66848769 -0.77779267 -0.44051826 -0.76004496  0.10363559]]
rank = 4 

[[-1.74725858 -2.52083677  1.07458242  1.23982343  0.44724371  0.44724371]
 [-0.04464538  0.76412724 -0.93559785  1.64392921 -0.3096506  -0.3096506 ]
 [ 0.75478467  0.02678163 -0.23610617  1.00405024 -0.65837617 -0.65837617]
 [-0.37989363  0.66848769 -0.77779267 -0.44051826 -0.76004496 -0.76004496]]
rank = 4 

[[-1.74725858 -2.52083677  1.07458242  1.23982343  0.44724371  0.44724371]
 [-0.04464538  0.76412724 -0.93559785  1.64392921 -0.3096506  -0.3096506 ]
 [ 0.75478467  0.02678163 -0.23610617  1.00405024 -0.65837617 -0.65837617]
 [ 0.75478467  0.02678163 -0.23610617  1.00405024 -0.65837617 -0.65837617]]
rank = 3


In [6]:
## adding noise to a rank-deficient matrix

# square for convenience
A = np.round( 10*np.random.randn(m,m) )

# reduce the rank
A[:,-1] = A[:,-2]

# noise level
noiseamp = .00000001  # tiny noise make the matrix FULL rank -> ML in Regularization!!
# noiseamp = .000000000000001 # not increase the rank

# add the noise
B = A + noiseamp*np.random.randn(m,m)

print('rank (w/o noise) = ' + str(np.linalg.matrix_rank(A)))
print('rank (with noise) = ' + str(np.linalg.matrix_rank(B)))


rank (w/o noise) = 3
rank (with noise) = 4


In [33]:
# know the limits of rank(A+B) and rank(AB)
# rank(A+B) <= ranK(A) + rank(B) => rank(A-B) is same since it is A + -1*B
# rank(AB) <= min(rank(A), rank(B))
# - AB = C => Abj = cj => rank(C) <= rank(A)
#          => aiB = ci => rank(B) <= rank(B)

In [38]:
# Code challenge: reduced-rank matrix via multiplication

# create a 10x10 matrix with rank=4 (use matrix multiplication)
import numpy as np

A = np.random.rand(10,4) @ np.random.rand(4, 10)
print(np.shape(A))
print(np.linalg.matrix_rank(A))

# generalize the procedure to create any MxN matrix with rank r

def reduced_rank(M, N, r):
    A = np.random.rand(M, r) @ np.random.rand(r, N)
    return np.shape(A), np.linalg.matrix_rank(A)

(10, 10)
4


In [40]:
print(reduced_rank(8, 47, 3))
print(reduced_rank(8, 47, 13))  # r > M, then rank will be M

((8, 47), 3)
((8, 47), 8)


In [42]:
# Code challenge: scalar multiplication and rank
# rank(A) = rank(l*A)

# create two matrices: full-rank and a reduced-rank
m = 6
n = 4
F = np.random.rand(m, n) @ np.random.rand(n, n)
R = np.random.rand(m, n-1) @ np.random.rand(n-1, n)

# create some scalar
l = 293428073  # only l = 0 can change the rank to 0

# rank of F, R, rank of l*F, l*R
print(np.linalg.matrix_rank(F), np.linalg.matrix_rank(R))
print(np.linalg.matrix_rank(l*F), np.linalg.matrix_rank(l*R))

# Check wheter rank(l*F) != l*rank(F)
print(np.linalg.matrix_rank(l*F) == l*np.linalg.matrix_rank(F))

4 3
4 3
False



---
# VIDEO: Rank of A^TA and AA^T
---


rank(A) == rank(A<sup>T</sup>A) == rank(A<sup>T</sup>) == rank(AA<sup>T</sup>)

In [ ]:
# matrix sizes
m = 14
n =  3

# create matrices
A = np.round( 10*np.random.randn(m,n) )

AtA = A.T@A
AAt = A@A.T

# get matrix sizes
sizeAtA = AtA.shape
sizeAAt = AAt.shape

# print info!
print('AtA: %dx%d, rank=%d' %(sizeAtA[0],sizeAtA[1],np.linalg.matrix_rank(AtA)))
print('AAt: %dx%d, rank=%d' %(sizeAAt[0],sizeAAt[1],np.linalg.matrix_rank(AAt)))


In [3]:
# Code challenges: rank of multiplied and summed matrices

# rules: rank of AB <= min( rank(A), rank(B) )
#        rank of A+B <= rank(A) + rank(B)

# generate two matrices : 2 x 5

import numpy as np

m, n = 2, 5
A = np.random.randn(m, n)
B = np.random.randn(m, n)

# compute AtA and BtB
AtA = A.T@A
BtB = B.T@B

# find ranks of AtA and BtB
print(np.linalg.matrix_rank(AtA), np.linalg.matrix_rank(BtB))  # rank 2, 2
print(np.linalg.matrix_rank(AtA@BtB))  # rank 2
print(np.linalg.matrix_rank(AtA+BtB))  # rank 4

2 2
2
4



---
# VIDEO: Making a matrix full-rank by "shifting"
---


In [7]:
# size of matrix
m = 30

# create the square symmetric matrix
A = np.random.randn(m,m)
A = np.round( 10 * A.T@A )
print('rank(original) = %d' %np.linalg.matrix_rank(A))

# reduce the rank
A[:,0] = A[:,1]  # copy col[1] to col[0]

# shift amount (l=lambda)
l = .01

# new matrix by shifting
B = A + l*np.eye(m,m)  # l * I (Identity matrix)

# print information
print('rank(w/o shift) = %d' %np.linalg.matrix_rank(A))
print('rank(with shift) = %d' %np.linalg.matrix_rank(B))


rank(original) = 30
rank(w/o shift) = 29
rank(with shift) = 30


In [12]:
# Code challenge: is this vector in the span of this set?

# determine whether this vector
v = np.array([[1, 2, 3, 4]]).T  # row vector - transpose -> column vector
print(v)

# in the span of these sets?
S = np.vstack(([4,3,6,2], [0,4,0,1])).T
T = np.vstack(([1,2,2,2], [0,0,1,2])).T
print(S)
# print(T)

Sv = np.concatenate((S, v), axis=1)
Tv = np.concatenate((T, v), axis=1)
print(Sv)
print(Tv)

print()
print(np.linalg.matrix_rank(Sv))  # rank 3 -> s does not span in S
print(np.linalg.matrix_rank(Tv))  # rank 2 -> v spans in T

[[1]
 [2]
 [3]
 [4]]
[[4 0]
 [3 4]
 [6 0]
 [2 1]]
[[4 0 1]
 [3 4 2]
 [6 0 3]
 [2 1 4]]
[[1 0 1]
 [2 0 2]
 [2 1 3]
 [2 2 4]]

3
2
