In [4]:
# Create a row vector and a column vector, and show their shape.

import numpy as np

vector_row = np.array([[1, -5, 3, 2, 4]])
vector_col = np.array([[1], [2], [3], [4]])

print(vector_row)
print(vector_row.shape)

print(vector_col)
print(vector_col.shape)

[[ 1 -5  3  2  4]]
(1, 5)
[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [6]:
# Transpose the row vector defined above into a column vector and calculate its L1, L2,
# and L∞ norm. Verify that the L∞ norm of a vector is equivalent to the maximum value of the
# elements in the vector.

from numpy.linalg import norm

new_vector = vector_row.T
print(new_vector)

norm_1 = norm(new_vector, 1)
norm_2 = norm(new_vector, 2)
norm_inf = norm(new_vector, np.inf)  # abs(maximum)

print(f'L_1 is {norm_1}')
print(f'L_2 is {norm_2}')
print(f'L_inf is {norm_inf}')

[[ 1]
 [-5]
 [ 3]
 [ 2]
 [ 4]]
L_1 is 15.0
L_2 is 7.416198487095664
L_inf is 5.0


In [10]:
# Show that a(v + w) = av +aw (i.e., scalar multiplication of a vector distributes across vector addition).

v = np.array([[1, 2, 3, 4]])
w = np.array([[5, 6, 7, 8]])

vec_add = 2 * (v + w)
print(vec_add)

v2 = 2 * v
w2 = 2 * w
vec_add2 = v2 + w2
print(vec_add2)


[[12 16 20 24]]
[[12 16 20 24]]


In [13]:
# Compute the angle between the vectors v = [10, 9, 3] and w = [2, 5, 12].

from numpy import arccos, dot

v = np.array([[10, 9, 3]])
w = np.array([[2, 5, 12]])
dot_v_w = dot(v, w.T)
print(dot_v_w)

theta = arccos(dot(v, w.T)/(norm(v)*norm(w)))
print(theta)

[[101]]
[[0.97992471]]


In [15]:
# Given the vectors v = [0, 2, 0] and w = [3, 0, 0], use the NumPy function cross to compute
# the cross-product of v and w.

v = np.array([[0, 2, 0]])
w = np.array([[3, 0, 0]])

print(np.cross(v, w))

[[ 0  0 -6]]


In [16]:
# Given the row vectors v = [0, 3, 2], w = [4, 1, 1], and u = [0,−2, 0], write the vector
# x = [−8,−1, 4] as a linear combination of v, w, and u.

v = np.array([[0, 3, 2]])
w = np.array([[4, 1, 1]])
u = np.array([[0, -2, 0]])
x = 3*v-2*w+4*u
print(x)

[[-8 -1  4]]


In [17]:
# Let matrices P and Q be [[1, 7], [2, 3], [5, 0]] and [[2, 6, 3, 1], [1, 2, 3, 4]], respectively. Compute
# the Python matrix product of P and Q. Show that the product of Q and P will produce an error.

P = np.array([[1, 7], [2, 3], [5, 0]])
Q = np.array([[2, 6, 3, 1], [1, 2, 3, 4]])
print(P)  # 3 x 2
print(Q)  # 2 x 4
print(np.dot(P, Q))  # 3 x 4
np.dot(Q, P)  # error

[[1 7]
 [2 3]
 [5 0]]
[[2 6 3 1]
 [1 2 3 4]]
[[ 9 20 24 29]
 [ 7 18 15 14]
 [10 30 15  5]]


ValueError: shapes (2,4) and (3,2) not aligned: 4 (dim 1) != 3 (dim 0)

In [18]:
# Find the determinant of matrix M = [[0, 2, 1, 3], [3, 2, 8, 1], [1, 0, 0, 3], [0, 3, 2, 1]]. Use the
# np.eye function to produce a 4×4 identity matrix, I . Multiply M by I to show that the result is M.

from numpy.linalg import det
M = np.array([[0,2,1,3],
              [3,2,8,1],
              [1,0,0,3],
              [0,3,2,1]])

print("M:\n", M)

print("Determinant: %.1f" % det(M))

I = np.eye(4)
print("I:\n", I)

print("M*I:\n", np.dot(M, I))

M:
 [[0 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 3 2 1]]
Determinant: -38.0
I:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
M*I:
 [[0. 2. 1. 3.]
 [3. 2. 8. 1.]
 [1. 0. 0. 3.]
 [0. 3. 2. 1.]]
